<?php

declare(strict_types=1);

namespace App\Service;

use Symfony\AI\Platform\Message\Content\Text;
use Symfony\AI\Platform\Message\MessageBag;
use Symfony\AI\Platform\Message\SystemMessage;
use Symfony\AI\Platform\Message\UserMessage;
use Symfony\AI\Platform\PlatformInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

use App\Ai\Tool\CreatePollTool;
use App\Ai\Tool\ScheduleReminderTool;
use Symfony\AI\Platform\Tool\ExecutionReference;
use Symfony\AI\Platform\Tool\Tool;

/**
 * Service dedicated to querying an LLM using the Symfony AI components.
 */
readonly class LlmService
{
    public function __construct(
        #[Autowire(service: 'ai.platform.generic.cloud')]
        private PlatformInterface $platform,
        private CreatePollTool $createPollTool,
        private ScheduleReminderTool $scheduleReminderTool,
        #[Autowire(env: 'LLM_MODEL')]
        private string $model,
        #[Autowire(env: 'LLM_SYSTEM_PROMPT')]
        private ?string $defaultSystemPrompt = null,
        private ?\Psr\Log\LoggerInterface $logger = null,
    ) {}

    public function getScheduleReminderTool(): ScheduleReminderTool
    {
        return $this->scheduleReminderTool;
    }

    /**
     * Generates a text response from a user prompt.
     *
     * @param string $prompt The user prompt to send to the model.
     * @param string|null $systemPrompt Optional override for the system prompt. If null, the default system prompt will be used.
     * @param array<string, mixed> $options Platform-specific options (e.g., temperature).
     * @return string The text output generated by the LLM.
     */
    public function generateText(string $prompt, ?string $systemPrompt = null, array $options = []): string
    {
        $text = '';
        foreach ($this->generateTextStream($prompt, $systemPrompt, $options) as $chunk) {
            $text .= $chunk;
        }

        return $text;
    }

    /**
     * Generates a text stream response from a user prompt.
     *
     * @param string $prompt The user prompt to send to the model.
     * @param string|null $systemPrompt Optional override for the system prompt.
     * @param array<string, mixed> $options Platform-specific options.
     * @return \Generator<string> Yields each text chunk.
     */
    public function generateTextStream(string $prompt, ?string $systemPrompt = null, array $options = []): \Generator
    {
        $messages = [];

        $activeSystemPrompt = $systemPrompt ?? $this->defaultSystemPrompt;
        if ($activeSystemPrompt !== null && $activeSystemPrompt !== '') {
            $messages[] = new SystemMessage($activeSystemPrompt);
        }

        $messages[] = new UserMessage(new Text($prompt));

        $messageBag = new MessageBag(...$messages);

        unset($options['stream']);
        $result = $this->platform->invoke($this->model, $messageBag, $options);
        $this->logger?->info('LlmService invoke called (non-stream)', ['model' => $this->model, 'resultClass' => get_class($result)]);
        yield $result->asText();
    }

    /**
     * Executes direct inference using a customized MessageBag.
     * Useful for complex conversations, memory handling, or few-shot prompts.
     *
     * @param MessageBag $messageBag Message history or collection.
     * @param array<string, mixed> $options Platform-specific options.
     * @return string The text output generated by the LLM.
     */
    public function chat(MessageBag $messageBag, array $options = []): string
    {
        $options['stream'] = true;

        $resultStream = $this->platform->invoke($this->model, $messageBag, $options)->asStream();
        $text = '';
        foreach ($resultStream as $delta) {
            if (!$delta instanceof \Symfony\AI\Platform\Result\Stream\Delta\TextDelta) {
                continue;
            }

            $text .= $delta->getText();
        }

        return $text;
    }
}
