<?php

declare(strict_types=1);

namespace App\Service;

use Symfony\AI\Platform\Message\Content\Text;
use Symfony\AI\Platform\Message\MessageBag;
use Symfony\AI\Platform\Message\SystemMessage;
use Symfony\AI\Platform\Message\UserMessage;
use Symfony\AI\Platform\PlatformInterface;
use Symfony\AI\Platform\Result\Stream\Delta\TextDelta;
use Symfony\AI\Platform\Result\Stream\Delta\ToolCallComplete;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

/**
 * Service dedicated to querying an LLM using the Symfony AI components.
 */
readonly class LlmService
{
    private LlmRetry $retry;

    public function __construct(
        #[Autowire(service: 'ai.platform.generic.cloud')]
        private PlatformInterface $platform,
        #[Autowire(env: 'LLM_MODEL')]
        private string $model,
        #[Autowire(env: 'LLM_SYSTEM_PROMPT')]
        private ?string $defaultSystemPrompt = null,
        private ?\Psr\Log\LoggerInterface $logger = null,
        #[Autowire(env: 'int:LLM_MAX_RETRIES')]
        private int $maxRetries = 2,
    ) {
        $this->retry = new LlmRetry($this->platform, $this->model, $this->maxRetries, $this->logger);
    }

    /**
     * Generates a text response from a user prompt.
     *
     * @param string $prompt The user prompt to send to the model.
     * @param string|null $systemPrompt Optional override for the system prompt. If null, the default system prompt will be used.
     * @param array<string, mixed> $options Platform-specific options (e.g., temperature).
     * @return string The text output generated by the LLM.
     */
    public function generateText(string $prompt, ?string $systemPrompt = null, array $options = []): string
    {
        $text = '';
        foreach ($this->generateTextStream($prompt, $systemPrompt, $options) as $chunk) {
            $text .= $chunk;
        }

        return $text;
    }

    /**
     * Streams the text response from a user prompt.
     *
     * @param string $prompt The user prompt to send to the model.
     * @param string|null $systemPrompt Optional override for the system prompt.
     * @param array<string, mixed> $options Platform-specific options.
     * @return \Generator<string> Yields each text chunk.
     */
    public function generateTextStream(string $prompt, ?string $systemPrompt = null, array $options = []): \Generator
    {
        foreach ($this->generateStream($prompt, $systemPrompt, $options) as $delta) {
            if (!$delta instanceof TextDelta) {
                continue;
            }

            yield $delta->getText();
        }
    }

    /**
     * Streams an LLM invocation that may request tool calls.
     *
     * @param string $prompt The user prompt to send to the model.
     * @param string|null $systemPrompt Optional override for the system prompt.
     * @param list<array{type: string, function: array<string, mixed>}> $tools Normalized OpenAI tool definitions.
     * @param array<string, mixed> $options Platform-specific options.
     * @return \Generator<TextDelta|ToolCallComplete> Yields text deltas and, once complete, the requested tool calls.
     */
    public function generateStreamWithTools(
        string $prompt,
        ?string $systemPrompt,
        array $tools,
        array $options = [],
    ): \Generator {
        $options['tools'] = $tools;

        yield from $this->generateStream($prompt, $systemPrompt, $options);
    }

    /**
     * @param array<string, mixed> $options Platform-specific options.
     * @return \Generator<TextDelta|ToolCallComplete>
     */
    private function generateStream(string $prompt, ?string $systemPrompt = null, array $options = []): \Generator
    {
        $messages = [];

        $activeSystemPrompt = $systemPrompt ?? $this->defaultSystemPrompt;
        if ($activeSystemPrompt !== null && $activeSystemPrompt !== '') {
            $messages[] = new SystemMessage($activeSystemPrompt);
        }

        $messages[] = new UserMessage(new Text($prompt));

        $messageBag = new MessageBag(...$messages);

        $options['stream'] = true;

        yield from $this->retry->stream($messageBag, $options);
    }

    /**
     * Executes direct inference using a customized MessageBag.
     * Useful for complex conversations, memory handling, or few-shot prompts.
     *
     * @param MessageBag $messageBag Message history or collection.
     * @param array<string, mixed> $options Platform-specific options.
     * @return string The text output generated by the LLM.
     */
    public function chat(MessageBag $messageBag, array $options = []): string
    {
        $options['stream'] = true;

        $text = '';
        foreach ($this->retry->stream($messageBag, $options) as $delta) {
            if (!$delta instanceof TextDelta) {
                continue;
            }

            $text .= $delta->getText();
        }

        return $text;
    }
}
