#:schema https://mago.carthage.software/1.29.0/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.4.0"

[source]
workspace = "."
paths = ["mate/src/", "src/", "tests/"]
excludes = ["vendor"]

[source.glob]
literal-separator = true

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["symfony", "phpunit"]

[linter.rules]
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
kan-defect = { enabled = false }

[analyzer]
plugins = []
find-unused-definitions = true
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
unchecked-exceptions = ["Error", "LogicException"]
unchecked-exception-classes = []
strict-list-index-checks = false
strict-array-index-existence = false
allow-array-truthy-operand = false
no-boolean-literal-comparison = false
register-super-globals = true
