<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260613165139 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "channel_export" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, file_size INT NOT NULL, channel_name VARCHAR(255) NOT NULL, channel_id INT DEFAULT NULL, exported_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BCEF2CEA72F5A1AA ON "channel_export" (channel_id)');
        $this->addSql('CREATE INDEX IDX_BCEF2CEAF748B80E ON "channel_export" (exported_by_id)');
        $this->addSql('ALTER TABLE "channel_export" ADD CONSTRAINT FK_BCEF2CEA72F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "channel_export" ADD CONSTRAINT FK_BCEF2CEAF748B80E FOREIGN KEY (exported_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_group_official_channel');
        $this->addSql('CREATE UNIQUE INDEX uniq_group_official_channel ON group_subscription (group_identifier) WHERE is_group_channel = true');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "channel_export" DROP CONSTRAINT FK_BCEF2CEA72F5A1AA');
        $this->addSql('ALTER TABLE "channel_export" DROP CONSTRAINT FK_BCEF2CEAF748B80E');
        $this->addSql('DROP TABLE "channel_export"');
        $this->addSql('DROP INDEX uniq_group_official_channel');
        $this->addSql('CREATE UNIQUE INDEX uniq_group_official_channel ON "group_subscription" (group_identifier) WHERE (is_group_channel = true)');
    }
}
