<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608182926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE "webhook" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, channel_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A7417565F37A13B ON "webhook" (token)');
        $this->addSql('CREATE INDEX IDX_8A74175672F5A1AA ON "webhook" (channel_id)');
        $this->addSql('CREATE INDEX IDX_8A74175661220EA6 ON "webhook" (creator_id)');
        $this->addSql(
            'ALTER TABLE "webhook" ADD CONSTRAINT FK_8A74175672F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE CASCADE NOT DEFERRABLE',
        );
        $this->addSql(
            'ALTER TABLE "webhook" ADD CONSTRAINT FK_8A74175661220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE',
        );
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307f727aca70');
        $this->addSql('DROP INDEX idx_message_channel_parent');
        $this->addSql('DROP INDEX idx_message_parent');
        $this->addSql('ALTER TABLE message DROP parent_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "webhook" DROP CONSTRAINT FK_8A74175672F5A1AA');
        $this->addSql('ALTER TABLE "webhook" DROP CONSTRAINT FK_8A74175661220EA6');
        $this->addSql('DROP TABLE "webhook"');
        $this->addSql('ALTER TABLE "message" ADD parent_id INT DEFAULT NULL');
        $this->addSql(
            'ALTER TABLE "message" ADD CONSTRAINT fk_b6bd307f727aca70 FOREIGN KEY (parent_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );
        $this->addSql('CREATE INDEX idx_message_channel_parent ON "message" (channel_id, parent_id)');
        $this->addSql('CREATE INDEX idx_message_parent ON "message" (parent_id)');
    }
}
