<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260620120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create push_subscription table for Web Push subscriptions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "push_subscription" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            endpoint VARCHAR(512) NOT NULL,
            public_key VARCHAR(255) NOT NULL,
            auth_token VARCHAR(255) NOT NULL,
            user_agent VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_push_subscription_user ON "push_subscription" (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PUSH_USER_ENDPOINT ON "push_subscription" (user_id, endpoint)');
        $this->addSql('ALTER TABLE "push_subscription" ADD CONSTRAINT FK_push_subscription_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "push_subscription"');
    }
}
