<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260704000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add workspace entity and migrate channels to workspaces';
    }

    public function up(Schema $schema): void
    {
        // 1. Create workspace table
        $this->addSql('CREATE TABLE "workspace" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            creator_id INT DEFAULT NULL,
            name VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            description VARCHAR(255) DEFAULT NULL,
            is_public BOOLEAN DEFAULT false NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WORKSPACE_SLUG ON "workspace" (slug)');
        $this->addSql('CREATE INDEX IDX_WORKSPACE_CREATOR ON "workspace" (creator_id)');
        $this->addSql('COMMENT ON COLUMN "workspace".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "workspace" ADD CONSTRAINT FK_WORKSPACE_CREATOR FOREIGN KEY (creator_id) REFERENCES "user"(id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // 2. Create workspace_user join table
        $this->addSql('CREATE TABLE workspace_user (
            workspace_id INT NOT NULL,
            user_id INT NOT NULL,
            PRIMARY KEY(workspace_id, user_id)
        )');
        $this->addSql('CREATE INDEX IDX_WU_WORKSPACE ON workspace_user (workspace_id)');
        $this->addSql('CREATE INDEX IDX_WU_USER ON workspace_user (user_id)');
        $this->addSql('ALTER TABLE workspace_user ADD CONSTRAINT FK_WU_WORKSPACE FOREIGN KEY (workspace_id) REFERENCES "workspace"(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE workspace_user ADD CONSTRAINT FK_WU_USER FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // 3. Add workspace_id to channel table
        $this->addSql('ALTER TABLE "channel" ADD workspace_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_CHANNEL_WORKSPACE ON "channel" (workspace_id)');
        $this->addSql('ALTER TABLE "channel" ADD CONSTRAINT FK_CHANNEL_WORKSPACE FOREIGN KEY (workspace_id) REFERENCES "workspace"(id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // 3b. Add workspace_id to invitation table
        $this->addSql('ALTER TABLE "invitation" ADD workspace_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "invitation" ALTER channel_id DROP NOT NULL');
        $this->addSql('CREATE INDEX IDX_INVITATION_WORKSPACE ON "invitation" (workspace_id)');
        $this->addSql('ALTER TABLE "invitation" ADD CONSTRAINT FK_INVITATION_WORKSPACE FOREIGN KEY (workspace_id) REFERENCES "workspace"(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // 4. Create the "Public" workspace
        $this->addSql("INSERT INTO \"workspace\" (name, slug, description, is_public, created_at)
            VALUES ('Public', 'public', 'Espace public ouvert à tous les utilisateurs.', true, NOW())");

        // 5. Add all existing users to the Public workspace
        $this->addSql('INSERT INTO workspace_user (workspace_id, user_id)
            SELECT (SELECT id FROM "workspace" WHERE slug = \'public\'), u.id
            FROM "user" u');

        // 6. Move public channels (is_private=false, is_dm=false, parent_message_id IS NULL) to Public workspace
        $this->addSql('UPDATE "channel" SET workspace_id = (SELECT id FROM "workspace" WHERE slug = \'public\')
            WHERE is_private = false AND is_dm = false AND parent_message_id IS NULL');

        // 7. For each private channel (is_private=true, is_dm=false, parent_message_id IS NULL):
        //    Create a workspace, rename channel to "général"/"general", add members
        $this->addSql("
            DO \$\$
            DECLARE
                ch RECORD;
                new_workspace_id INT;
                w_count INT := 0;
                workspace_slug TEXT;
                base_slug TEXT;
            BEGIN
                FOR ch IN SELECT * FROM \"channel\" WHERE is_private = true AND is_dm = false AND parent_message_id IS NULL
                LOOP
                    -- Generate a unique slug for the workspace
                    base_slug := lower(regexp_replace(ch.name, '[^a-z0-9]+', '-', 'g'));
                    IF base_slug = '' OR base_slug IS NULL THEN
                        base_slug := 'workspace';
                    END IF;
                    workspace_slug := base_slug;
                    w_count := 0;
                    LOOP
                        EXIT WHEN NOT EXISTS (SELECT 1 FROM \"workspace\" WHERE slug = workspace_slug);
                        w_count := w_count + 1;
                        workspace_slug := base_slug || '-' || w_count::TEXT;
                    END LOOP;

                    INSERT INTO \"workspace\" (name, slug, description, is_public, created_at, creator_id)
                    VALUES (ch.name, workspace_slug, ch.description, false, ch.created_at, ch.creator_id)
                    RETURNING id INTO new_workspace_id;

                    -- Add all channel members to workspace
                    INSERT INTO workspace_user (workspace_id, user_id)
                    SELECT new_workspace_id, cu.user_id
                    FROM channel_user cu
                    WHERE cu.channel_id = ch.id
                    ON CONFLICT DO NOTHING;

                    -- Add the channel creator if not already a member
                    IF ch.creator_id IS NOT NULL THEN
                        INSERT INTO workspace_user (workspace_id, user_id)
                        SELECT new_workspace_id, ch.creator_id
                        WHERE NOT EXISTS (
                            SELECT 1 FROM workspace_user WHERE workspace_id = new_workspace_id AND user_id = ch.creator_id
                        );
                    END IF;

                    -- Rename channel to 'général' and link to workspace
                    UPDATE \"channel\" SET name = 'général', workspace_id = new_workspace_id WHERE id = ch.id;
                END LOOP;
            END \$\$;
        ");

        // 8. Migrate sub-channels (parent_message_id IS NOT NULL) — follow their parent's workspace
        //    Sub-channels inherit workspace from the channel of their parent message
        $this->addSql('UPDATE "channel" AS sc
            SET workspace_id = pc.workspace_id
            FROM "message" AS m
            JOIN "channel" AS pc ON pc.id = m.channel_id
            WHERE sc.parent_message_id = m.id
            AND sc.workspace_id IS NULL');
    }

    public function down(Schema $schema): void
    {
        // Reverse: remove workspace from channels
        $this->addSql('UPDATE "channel" SET workspace_id = NULL');

        // Remove workspace data
        $this->addSql('ALTER TABLE "channel" DROP CONSTRAINT IF EXISTS FK_CHANNEL_WORKSPACE');
        $this->addSql('DROP INDEX IF EXISTS IDX_CHANNEL_WORKSPACE');
        $this->addSql('ALTER TABLE "channel" DROP workspace_id');

        // Remove workspace from invitations
        $this->addSql('ALTER TABLE "invitation" DROP CONSTRAINT IF EXISTS FK_INVITATION_WORKSPACE');
        $this->addSql('DROP INDEX IF EXISTS IDX_INVITATION_WORKSPACE');
        $this->addSql('ALTER TABLE "invitation" DROP workspace_id');
        $this->addSql('ALTER TABLE "invitation" ALTER channel_id SET NOT NULL');

        $this->addSql('ALTER TABLE workspace_user DROP CONSTRAINT IF EXISTS FK_WU_WORKSPACE');
        $this->addSql('ALTER TABLE workspace_user DROP CONSTRAINT IF EXISTS FK_WU_USER');
        $this->addSql('DROP TABLE workspace_user');
        $this->addSql('DROP TABLE "workspace"');
    }
}
