<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260528084659 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "reaction" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, emoji VARCHAR(32) NOT NULL, message_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4D707F7537A1329 ON "reaction" (message_id)');
        $this->addSql('CREATE INDEX IDX_A4D707F7A76ED395 ON "reaction" (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_message_user_emoji ON "reaction" (message_id, user_id, emoji)');
        $this->addSql('ALTER TABLE "reaction" ADD CONSTRAINT FK_A4D707F7537A1329 FOREIGN KEY (message_id) REFERENCES "message" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "reaction" ADD CONSTRAINT FK_A4D707F7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "reaction" DROP CONSTRAINT FK_A4D707F7537A1329');
        $this->addSql('ALTER TABLE "reaction" DROP CONSTRAINT FK_A4D707F7A76ED395');
        $this->addSql('DROP TABLE "reaction"');
    }
}
