<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527175543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, channel_id INT NOT NULL, invitee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11D61A272F5A1AA ON invitation (channel_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A27A512022 ON invitation (invitee_id)');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A272F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A27A512022 FOREIGN KEY (invitee_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A272F5A1AA');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A27A512022');
        $this->addSql('DROP TABLE invitation');
    }
}
