<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612150522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "group_subscription" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_identifier VARCHAR(255) NOT NULL, is_group_channel BOOLEAN DEFAULT false NOT NULL, channel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F802EEA72F5A1AA ON "group_subscription" (channel_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_group_official_channel ON "group_subscription" (group_identifier) WHERE is_group_channel = true');
        $this->addSql('ALTER TABLE "group_subscription" ADD CONSTRAINT FK_4F802EEA72F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "group_subscription" DROP CONSTRAINT FK_4F802EEA72F5A1AA');
        $this->addSql('DROP TABLE "group_subscription"');
    }
}
