<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527162924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user_channel_read" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, channel_id INT NOT NULL, last_read_message_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84CF9E1BA76ED395 ON "user_channel_read" (user_id)');
        $this->addSql('CREATE INDEX IDX_84CF9E1B72F5A1AA ON "user_channel_read" (channel_id)');
        $this->addSql('CREATE INDEX IDX_84CF9E1B384BCFBF ON "user_channel_read" (last_read_message_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_CHANNEL ON "user_channel_read" (user_id, channel_id)');
        $this->addSql('ALTER TABLE "user_channel_read" ADD CONSTRAINT FK_84CF9E1BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user_channel_read" ADD CONSTRAINT FK_84CF9E1B72F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user_channel_read" ADD CONSTRAINT FK_84CF9E1B384BCFBF FOREIGN KEY (last_read_message_id) REFERENCES "message" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user_channel_read" DROP CONSTRAINT FK_84CF9E1BA76ED395');
        $this->addSql('ALTER TABLE "user_channel_read" DROP CONSTRAINT FK_84CF9E1B72F5A1AA');
        $this->addSql('ALTER TABLE "user_channel_read" DROP CONSTRAINT FK_84CF9E1B384BCFBF');
        $this->addSql('DROP TABLE "user_channel_read"');
    }
}
