<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260531095040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_saved_messages (user_id INT NOT NULL, message_id INT NOT NULL, PRIMARY KEY (user_id, message_id))');
        $this->addSql('CREATE INDEX IDX_DE66C6E7A76ED395 ON user_saved_messages (user_id)');
        $this->addSql('CREATE INDEX IDX_DE66C6E7537A1329 ON user_saved_messages (message_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE user_saved_messages ADD CONSTRAINT FK_DE66C6E7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_saved_messages ADD CONSTRAINT FK_DE66C6E7537A1329 FOREIGN KEY (message_id) REFERENCES "message" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel ADD pinned_message_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE channel ADD CONSTRAINT FK_A2F98E47C254572F FOREIGN KEY (pinned_message_id) REFERENCES "message" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A2F98E47C254572F ON channel (pinned_message_id)');
        $this->addSql('ALTER TABLE "user" ADD custom_hue INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD display_name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD last_active_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD status_override VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD mention_notifications_enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE user_channel_read ADD notifications_enabled BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_saved_messages DROP CONSTRAINT FK_DE66C6E7A76ED395');
        $this->addSql('ALTER TABLE user_saved_messages DROP CONSTRAINT FK_DE66C6E7537A1329');
        $this->addSql('DROP TABLE user_saved_messages');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE "channel" DROP CONSTRAINT FK_A2F98E47C254572F');
        $this->addSql('DROP INDEX IDX_A2F98E47C254572F');
        $this->addSql('ALTER TABLE "channel" DROP pinned_message_id');
        $this->addSql('ALTER TABLE "user" DROP custom_hue');
        $this->addSql('ALTER TABLE "user" DROP display_name');
        $this->addSql('ALTER TABLE "user" DROP last_active_at');
        $this->addSql('ALTER TABLE "user" DROP status_override');
        $this->addSql('ALTER TABLE "user" DROP mention_notifications_enabled');
        $this->addSql('ALTER TABLE "user_channel_read" DROP notifications_enabled');
    }
}
