<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Creates the poll, poll_option, and poll_vote tables and constraints.
 */
final class Version20260603130438 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create poll, poll_option, and poll_vote tables and foreign keys.';
    }

    public function up(Schema $schema): void
    {
        // Create tables
        $this->addSql('CREATE TABLE "poll" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(255) NOT NULL, allow_multiple BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84BCFA45537A1329 ON "poll" (message_id)');

        $this->addSql('CREATE TABLE "poll_option" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text VARCHAR(255) NOT NULL, position INT NOT NULL, poll_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B68343EB3C947C0F ON "poll_option" (poll_id)');

        $this->addSql('CREATE TABLE "poll_vote" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED568EBEA76ED395 ON "poll_vote" (user_id)');
        $this->addSql('CREATE INDEX IDX_ED568EBEA7C41D6F ON "poll_vote" (option_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_poll_option ON "poll_vote" (user_id, option_id)');

        // Add foreign key constraints
        $this->addSql('ALTER TABLE "poll" ADD CONSTRAINT FK_84BCFA45537A1329 FOREIGN KEY (message_id) REFERENCES "message" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "poll_option" ADD CONSTRAINT FK_B68343EB3C947C0F FOREIGN KEY (poll_id) REFERENCES "poll" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "poll_vote" ADD CONSTRAINT FK_ED568EBEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "poll_vote" ADD CONSTRAINT FK_ED568EBEA7C41D6F FOREIGN KEY (option_id) REFERENCES "poll_option" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "poll" DROP CONSTRAINT FK_84BCFA45537A1329');
        $this->addSql('ALTER TABLE "poll_option" DROP CONSTRAINT FK_B68343EB3C947C0F');
        $this->addSql('ALTER TABLE "poll_vote" DROP CONSTRAINT FK_ED568EBEA76ED395');
        $this->addSql('ALTER TABLE "poll_vote" DROP CONSTRAINT FK_ED568EBEA7C41D6F');

        $this->addSql('DROP TABLE "poll"');
        $this->addSql('DROP TABLE "poll_option"');
        $this->addSql('DROP TABLE "poll_vote"');
    }
}
