<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260705120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add kanban columns and message task metadata';
    }

    public function up(Schema $schema): void
    {
        // Create kanban_column table
        $this->addSql('CREATE TABLE kanban_column (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            channel_id INT NOT NULL,
            name VARCHAR(255) NOT NULL,
            position INT NOT NULL,
            color VARCHAR(7) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_kanban_channel_position ON kanban_column (channel_id, position)');
        $this->addSql('CREATE INDEX IDX_70DB6A0872F5A1AA ON kanban_column (channel_id)');
        $this->addSql('COMMENT ON COLUMN kanban_column.created_at IS \'(DC2Type:datetime_immutable)\'');

        // Add columns to message
        $this->addSql('ALTER TABLE "message" ADD kanban_column_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "message" ADD assigned_to_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "message" ADD due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "message" ADD priority VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE "message" ADD labels JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE "message" ADD is_completed BOOLEAN DEFAULT false NOT NULL');

        // Add indexes
        $this->addSql('CREATE INDEX idx_message_kanban_column ON "message" (kanban_column_id)');
        $this->addSql('CREATE INDEX idx_message_assigned_to ON "message" (assigned_to_id)');

        // Add foreign keys
        $this->addSql('ALTER TABLE kanban_column ADD CONSTRAINT FK_70DB6A0872F5A1AA FOREIGN KEY (channel_id) REFERENCES "channel" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "message" ADD CONSTRAINT FK_B6BD307F3AB77DBE FOREIGN KEY (kanban_column_id) REFERENCES kanban_column (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "message" ADD CONSTRAINT FK_B6BD307FF4A6199F FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Seed default columns for existing todo channels
        $this->addSql('
            INSERT INTO kanban_column (channel_id, name, position, color, created_at)
            SELECT
                c.id,
                \'À faire\',
                0,
                NULL,
                NOW()
            FROM "channel" c
            WHERE c.is_todo_list = true
        ');

        $this->addSql('
            INSERT INTO kanban_column (channel_id, name, position, color, created_at)
            SELECT
                c.id,
                \'En cours\',
                1,
                NULL,
                NOW()
            FROM "channel" c
            WHERE c.is_todo_list = true
        ');

        $this->addSql('
            INSERT INTO kanban_column (channel_id, name, position, color, created_at)
            SELECT
                c.id,
                \'Terminé\',
                2,
                NULL,
                NOW()
            FROM "channel" c
            WHERE c.is_todo_list = true
        ');

        // Assign existing messages in todo channels to the first column (À faire)
        $this->addSql('
            UPDATE "message" m
            SET kanban_column_id = kc.id
            FROM kanban_column kc
            JOIN "channel" c ON kc.channel_id = c.id
            WHERE m.channel_id = c.id
              AND kc.position = 0
              AND c.is_todo_list = true
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "message" DROP CONSTRAINT FK_B6BD307F3AB77DBE');
        $this->addSql('ALTER TABLE "message" DROP CONSTRAINT FK_B6BD307FF4A6199F');
        $this->addSql('ALTER TABLE kanban_column DROP CONSTRAINT FK_70DB6A0872F5A1AA');

        $this->addSql('DROP INDEX idx_message_kanban_column');
        $this->addSql('DROP INDEX idx_message_assigned_to');

        $this->addSql('ALTER TABLE "message" DROP kanban_column_id');
        $this->addSql('ALTER TABLE "message" DROP assigned_to_id');
        $this->addSql('ALTER TABLE "message" DROP due_at');
        $this->addSql('ALTER TABLE "message" DROP priority');
        $this->addSql('ALTER TABLE "message" DROP labels');
        $this->addSql('ALTER TABLE "message" DROP is_completed');

        $this->addSql('DROP TABLE kanban_column');
    }
}
